// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

declare module "prisma" {
  export function defineConfig(config: any): any;
}

import { defineConfig } from "prisma";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: (globalThis as any).process?.env?.DATABASE_URL,
  },
});
